# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:\\Program Files\\Java\\jdk-25
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=2.3
maven_group=mchorse
archives_base_name=bbs

# Dependencies
fabric_version=0.154.0+26.2